### ISSUE TITLE
Observer timeout

### ISSUE THREAD

**Issue by dominionish** [jimsch/CoAP-CSharp#5] opened 2017-05-23 17:39 UTC
##Good day!

I use you library for having comminication with sensortag by Coap protocol.
But I have a problem after long time observe.
I do this:

Request request = GetRequest(type);
request.AckTimeout = -1; //To make timeout unlimit
request.Respond += (s, e) => method(s, e, new Guid(guid));
request.MarkObserve();

So it work, but after 10-12 hours timeout is occured and observer didnt work. I should observe to resource again. Why do it happen?

My sensortag sleep one hour then wakeup, send data by coap to client and sleep again

**Comment by jimsch** [comment] 2017-05-23 18:10
Can you verify that the sensor did send a message at the time you think it timed out.  I don't remember any timeout code, but it might exist.

**Comment by dominionish** [comment] 2017-05-23 18:24
Hello, jimsch! I used COAP.NET repository - https://github.com/smeshlink/CoAP.NET. Is there any different between yours and this? And can you tell me how did you implement observer?
In COAP.NET observer implementation is not correct. It apways poll server, but need to subscribe to resource and get data when it recieve from server.

**Comment by jimsch** [comment] 2017-05-23 19:19
As acknowledged in the README,  I basically took a version of that repository and have been doing lots of work on it.  I don't believe that I have done any work on observer, however the behavior that you are showing is not what I am seeing.  A wireshark of the conversation that you are reporting would be interesting as I could then see what the exact behavior you are seeing is.  When I attempted to do the same thing you have suggested using the client and server examples, I only saw a single get followed by lots of responses.

**Comment by Moskus** [comment] 2017-05-23 20:42
I've seen the same, but with much, MUCH shorter intervals. If I reach 30 seconds I'm surprised...

**Comment by jimsch** [comment] 2017-05-23 22:18
OK - I have reproduce this.  I will look at it later.

**Comment by jimsch** [comment] 2017-05-23 23:40
Do your responses have a max age value in them?

**Comment by jimsch** [comment] 2017-05-24 17:33
I have created a new issue for polling #6 because I am not convinced that it was the original problem that was reported.

**Comment by dominionish** [comment] 2017-05-24 19:27
Yes responses have max age value = 60. But as i saw Response value 60 is default value when response created. So I tryed to change it, but observer become not working. So I think I should try your repository soon instead Sharp.NET

**Comment by jimsch** [comment] 2017-06-23 18:22
This is all fixed now - was a firewall issue

**Closed by jimsch** 2017-06-23 18:22 UTC
